INSERT INTO public.usuario (nome, login, senha) VALUES
('Admin', 'admin', 'MTIzNDU2'); -- senha: 123456

INSERT INTO public.tipo_transacao (titulo, descricao) VALUES
('Pagar', 'Realizar um pagamento ou uma compra.'),
('Receber', 'Registrar um recebimento.');

INSERT INTO public.categoria (id_usuario, titulo, descricao) VALUES
(1, 'Alimentação', 'Gastos com refeições diárias, compras de mercado e alimentação fora de casa'),
(1, 'Assinaturas', 'Serviços recorrentes como streaming, apps e clubes de assinatura'),
(1, 'Compras', 'Aquisições de produtos diversos e bens duráveis'),
(1, 'Cuidados Pessoais', 'Gastos com beleza, bem-estar e itens pessoais'),
(1, 'Despesas Profissionais', 'Custos relacionados à atividade profissional'),
(1, 'Dívidas e Empréstimos', 'Controle de todos os tipos de dívidas, parcelamentos e empréstimos realizados ou tomados'),
(1, 'Doações', 'Contribuições para caridade, presentes e ajudas financeiras'),
(1, 'Educação', 'Investimentos em cursos, materiais escolares e capacitação profissional'),
(1, 'Impostos', 'Tributos e taxas governamentais'),
(1, 'Investimentos', 'Aportes em ativos financeiros diversos'),
(1, 'Lazer', 'Gastos com entretenimento, viagens, hobbies e atividades recreativas'),
(1, 'Moradia', 'Despesas com aluguel, condomínio, manutenção e serviços da residência'),
(1, 'Planejamento Financeiro', 'Reservas para metas específicas, fundos de emergência e planejamento de longo prazo'),
(1, 'Receitas', 'Todas as entradas de dinheiro, incluindo salário e rendimentos diversos'),
(1, 'Saúde', 'Gastos médicos, medicamentos, planos de saúde e bem-estar físico'),
(1, 'Transporte', 'Despesas com locomoção, veículos e transporte público'),
(1, 'Vestuário', 'Compras de roupas, calçados e acessórios'),
(1, 'Outros', 'Transações que não se enquadram nas categorias anteriores');

INSERT INTO public.subcategoria (id_usuario, id_categoria, titulo) VALUES
-- Alimentação
(1, 1, 'Almoço'),
(1, 1, 'Bebidas'),
(1, 1, 'Café da Manhã'),
(1, 1, 'Delivery'),
(1, 1, 'Dieta'),
(1, 1, 'Feira/Hortifruti'),
(1, 1, 'Jantar'),
(1, 1, 'Lanche'),
(1, 1, 'Padaria'),
(1, 1, 'Supermercado'),
-- Assinaturas
(1, 2, 'Aplicativos'),
(1, 2, 'Clubes de Assinatura'),
(1, 2, 'Ferramentas de Produtividade'),
(1, 2, 'Revistas/Jornais'),
(1, 2, 'Serviços Cloud'),
(1, 2, 'Streaming de Música'),
(1, 2, 'Streaming de Vídeo'),
(1, 2, 'TV por Assinatura'),
(1, 2, 'VPN/Antivírus'),
-- Compras
(1, 3, 'Decoração'),
(1, 3, 'Eletrônicos'),
(1, 3, 'Eletrodomésticos'),
(1, 3, 'Itens para Casa'),
(1, 3, 'Móveis'),
(1, 3, 'Presentes'),
(1, 3, 'Tecnologia'),
-- Cuidados Pessoais
(1, 4, 'Barbearia'),
(1, 4, 'Cabelereiro'),
(1, 4, 'Cosméticos'),
(1, 4, 'Manicure/Pedicure'),
(1, 4, 'Produtos de Higiene'),
(1, 4, 'Spa/Massagem'),
(1, 4, 'Tratamentos Estéticos'),
-- Despesas Profissionais
(1, 5, 'Alimentação no Trabalho'),
(1, 5, 'Cursos e Capacitação'),
(1, 5, 'Equipamentos'),
(1, 5, 'Eventos Profissionais'),
(1, 5, 'Material de Escritório'),
(1, 5, 'Softwares'),
(1, 5, 'Transporte para Trabalho'),
-- Dívidas e Empréstimos
(1, 6, 'Cheque Especial'),
(1, 6, 'Dívida'),
(1, 6, 'Empréstimo'),
(1, 6, 'Financiamento'),
(1, 6, 'Juros'),
-- Doações
(1, 7, 'Campanhas'),
(1, 7, 'Caridade'),
(1, 7, 'Contribuições'),
(1, 7, 'Presentes'),
-- Educação
(1, 8, 'Certificações'),
(1, 8, 'Cursos Online'),
(1, 8, 'Faculdade'),
(1, 8, 'Idiomas'),
(1, 8, 'Livros'),
(1, 8, 'Material Escolar'),
(1, 8, 'Mensalidades Escolares'),
(1, 8, 'Workshops/Eventos'),
-- Impostos
(1, 9, 'Imposto de Renda'),
(1, 9, 'IPTU'),
(1, 9, 'IPVA'),
(1, 9, 'Taxas Diversas'),
(1, 9, 'Taxas Estaduais'),
(1, 9, 'Taxas Federais'),
(1, 9, 'Taxas Municipais'),
-- Investimentos
(1, 10, 'Ações'),
(1, 10, 'Aplicação'),
(1, 10, 'Criptomoedas'),
(1, 10, 'Fundos de Investimento'),
(1, 10, 'Fundos Imobiliários'),
(1, 10, 'Dividendos'),
(1, 10, 'Previdência Privada'),
(1, 10, 'Poupança'),
(1, 10, 'Renda Fixa'),
(1, 10, 'Renda Variável'),
(1, 10, 'Tesouro Direto'),
-- Lazer
(1, 11, 'Bares'),
(1, 11, 'Cinema'),
(1, 11, 'Clube'),
(1, 11, 'Esportes'),
(1, 11, 'Festas'),
(1, 11, 'Hobby'),
(1, 11, 'Jogos'),
(1, 11, 'Parques'),
(1, 11, 'Restaurantes'),
(1, 11, 'Shows/Eventos'),
(1, 11, 'Viagens'),
-- Moradia
(1, 12, 'Água'),
(1, 12, 'Aluguel'),
(1, 12, 'Condomínio'),
(1, 12, 'Gás'),
(1, 12, 'Internet'),
(1, 12, 'IPTU'),
(1, 12, 'Luz'),
(1, 12, 'Manutenção'),
(1, 12, 'Mobília'),
(1, 12, 'Produtos de Limpeza'),
(1, 12, 'Seguro Residencial'),
(1, 12, 'Serviços Domésticos'),
-- Receitas
(1, 13, 'Aluguel de Imóveis'),
(1, 13, 'Auxílios Governamentais'),
(1, 13, 'Bônus/Comissão'),
(1, 13, 'Décimo Terceiro'),
(1, 13, 'Fatura'),
(1, 13, 'Férias'),
(1, 13, 'Freelance'),
(1, 13, 'Hora Extra'),
(1, 13, 'Reembolsos'),
(1, 13, 'Rendimentos'),
(1, 13, 'Salário'),
(1, 13, 'Vendas'),
-- Planejamento Financeiro
(1, 14, 'Reserva'),
(1, 14, 'Meta'),
-- Saúde
(1, 15, 'Academia'),
(1, 15, 'Atividades Físicas'),
(1, 15, 'Dentista'),
(1, 15, 'Exames'),
(1, 15, 'Farmácia'),
(1, 15, 'Médico'),
(1, 15, 'Plano de Saúde'),
(1, 15, 'Suplementos'),
(1, 15, 'Terapia/Psicólogo'),
(1, 15, 'Tratamentos'),
-- Transporte
(1, 16, 'Aluguel de Veículos'),
(1, 16, 'Combustível'),
(1, 16, 'Estacionamento'),
(1, 16, 'IPVA/Licenciamento'),
(1, 16, 'Manutenção'),
(1, 16, 'Ônibus/Metrô'),
(1, 16, 'Passagens Aéreas'),
(1, 16, 'Pedágio'),
(1, 16, 'Seguro Veicular'),
(1, 16, 'Táxi/Aplicativos'),
-- Vestuário
(1, 17, 'Acessórios'),
(1, 17, 'Calçados'),
(1, 17, 'Joias/Bijuterias'),
(1, 17, 'Roupas'),
(1, 17, 'Roupas Esportivas'),
-- Outros
(1, 18, 'Despesas Diversas'),
(1, 18, 'Despesas Inesperadas');